name: Verify CI
run-name: Verify ${{ github.ref_name }}

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verified:
    runs-on: ubuntu-latest
    needs:
      - fmtcheck
      - test
      - typecheck
    steps:
      - run: echo "Code of Federal Regulations subparts B of 10 CFR 433 and 10 CFR 435"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - name: pnpm i
        run: pnpm i
      - name: tsc
        run: pnpm typecheck

  fmtcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - name: pnpm i
        run: pnpm i
      - name: prettier
        run: pnpm fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - name: pnpm i
        run: pnpm i
      - name: node --test
        run: pnpm test
