name: publish @next

on:
  push:
    branches: [ main ]
    paths:
      - package.json
      - plugin.d.ts
      - plugin.js
      - pnpm-lock.yaml

jobs:

  publish:
    name: publish @next to npm
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      semver-bump: prerelease
