name: Publish to npm
run-name: Publish ${{ inputs.semver-bump }} release to npm

on:
  workflow_dispatch:
    inputs:
      semver-bump:
        description: Semver bump release type
        required: true
        type: choice
        default: prerelease
        options:
          - major
          - minor
          - patch
          - prerelease

concurrency: release

env:
  SEMVER_BUMP: ${{inputs.semver-bump}}

jobs:
  build-params:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ inputs.semver-bump != 'prerelease' }}
      npm-tag: ${{ inputs.semver-bump == 'prerelease' && 'next' || 'latest' }}
      prerelease: ${{ inputs.semver-bump == 'prerelease' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: validate release notes
        if: inputs.semver-bump != 'prerelease'
        run: npx --yes @eighty4/changelog check

  verified:
    uses: ./.github/workflows/ci_verify.yml

  git-tag:
    name: create release tag
    runs-on: ubuntu-latest
    needs: [build-params, verified]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: semver
        id: semver
        run: |
          GIT_TAG=$(npm version $SEMVER_BUMP --no-git-tag-version)
          VERSION=${GIT_TAG:1}
          echo "git-tag=$GIT_TAG" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - if: inputs.semver-bump != 'prerelease'
        run: npx --yes @eighty4/changelog rollover
      - env:
          GIT_TAG: ${{ steps.semver.outputs.git-tag }}
          NPM_TAG: ${{ needs.build-params.outputs.npm-tag }}
        run: |
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          git commit -am "publish $GIT_TAG to npm as \"@$NPM_TAG\""
          git tag $GIT_TAG
          git push --atomic origin main $GIT_TAG
    outputs:
      git-tag: ${{ steps.semver.outputs.git-tag }}
      version: ${{ steps.semver.outputs.version }}

  npm-publish:
    name: publish to npm
    needs: [build-params, git-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ needs.git-tag.outputs.git-tag }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TAG: ${{ needs.build-params.outputs.npm-tag }}
        run: pnpm publish --access public --tag $NPM_TAG --no-git-checks

  release-notes:
    needs: [build-params, git-tag, npm-publish]
    uses: ./.github/workflows/release_notes.yml
    with:
      git_tag: ${{ needs.git-tag.outputs.git-tag }}
      npm_version: ${{ needs.git-tag.outputs.version }}
      prerelease: ${{ needs.build-params.outputs.prerelease == 'true' }}

  gh-release:
    needs:
      - build-params
      - release-notes
      - git-tag
      - npm-publish
    permissions:
      contents: write
    uses: ./.github/workflows/gh_release.yml
    with:
      title: ${{ needs.git-tag.outputs.git-tag }}
      tag: ${{ needs.git-tag.outputs.git-tag }}
      release_notes: ${{ needs.release-notes.outputs.notes }}
      prerelease: ${{ needs.build-params.outputs.prerelease }}
      latest: ${{ needs.build-params.outputs.latest }}
    secrets: inherit
