name: verify

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    steps:
      - run: echo "Code of Federal Regulations subparts B of 10 CFR 433 and 10 CFR 435"

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: pnpm i
        run: pnpm i
      - name: tsc
        run: pnpm check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: pnpm i
        run: pnpm i
      - name: node --test
        run: pnpm test
